import { Product, Category, Comment } from './types';

const comments: Comment[] = [
  { id: 'c1', author: 'Ana García', text: '¡Excelente guía! Muy práctica y directa al grano. Me ayudó mucho a empezar.', date: '2024-05-10', rating: 5 },
  { id: 'c2', author: 'Carlos Pérez', text: 'Buen contenido, aunque esperaba algunos ejemplos más avanzados. Aún así, recomendable.', date: '2024-05-12', rating: 4 },
];

export const products: Product[] = [
  {
    id: 'p1',
    title: 'Guía Rápida de Marketing Digital',
    description: 'Una guía completa de 48 páginas con estrategias prácticas y accionables para lanzar tu primer curso online, atraer estudiantes y generar ventas. Incluye plantillas y checklists.',
    price: 350.00,
    format: Category.PDF,
    excerpt: '48 páginas con estrategias prácticas para lanzar tu curso.',
    thumbnail: 'https://picsum.photos/seed/pdf/600/400',
    previewUrl: '#',
    rating: 4.8,
    reviews: 25,
    comments: comments,
  },
  {
    id: 'p2',
    title: 'Pack de Audio: Meditaciones Guiadas',
    description: 'Una colección de 5 pistas de audio de alta calidad, cada una de 10 minutos, diseñadas para ayudarte a reducir el estrés, mejorar el enfoque y encontrar la calma en tu día a día.',
    price: 200.00,
    format: Category.Audio,
    excerpt: '5 pistas de 10 minutos para reducir el estrés.',
    thumbnail: 'https://picsum.photos/seed/audio/600/400',
    previewUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    rating: 5.0,
    reviews: 42,
    comments: [{ id: 'c3', author: 'Laura Martínez', text: 'La calidad del audio es increíble y las meditaciones son muy efectivas. Las uso a diario.', date: '2024-05-15', rating: 5 }],
  },
  {
    id: 'p3',
    title: 'Curso en Vídeo: Fotografía con Móvil',
    description: 'Aprende a tomar fotos impresionantes con tu smartphone. Este curso de 20 lecciones en vídeo cubre todo, desde la composición y la iluminación hasta la edición avanzada.',
    price: 950.00,
    format: Category.Video,
    excerpt: '20 lecciones con ejemplos prácticos y descargas.',
    thumbnail: 'https://picsum.photos/seed/video/600/400',
    previewUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
    rating: 4.5,
    reviews: 18,
    comments: [
        { id: 'c4', author: 'Javier Rodríguez', text: 'Muy buen curso, he mejorado mis fotos un montón.', date: '2024-04-20', rating: 5 },
        { id: 'c5', author: 'Sofía López', text: 'Me gustó, pero me hubiese gustado un módulo sobre fotografía nocturna.', date: '2024-04-22', rating: 4 },
    ],
  },
  {
    id: 'p4',
    title: 'Colección de Imágenes: Paisajes Urbanos',
    description: 'Un paquete de 25 fotografías de alta resolución (4K) de paisajes urbanos nocturnos, perfectas para fondos de pantalla, proyectos de diseño o uso comercial.',
    price: 500.00,
    format: Category.Image,
    excerpt: '25 fotos de alta resolución para tus proyectos.',
    thumbnail: 'https://picsum.photos/seed/image/600/400',
    rating: 4.9,
    reviews: 31,
    comments: [],
  },
  {
    id: 'p5',
    title: 'Podcast Exclusivo: Secretos del Emprendimiento',
    description: 'Una serie de 3 episodios de podcast con entrevistas a emprendedores exitosos que comparten sus historias, fracasos y las claves de su éxito. Acceso exclusivo a la serie completa.',
    price: 300.00,
    format: Category.Podcast,
    excerpt: '3 episodios con entrevistas a emprendedores exitosos.',
    thumbnail: 'https://picsum.photos/seed/podcast/600/400',
    previewUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    rating: 4.7,
    reviews: 12,
    comments: [],
  },
  {
    id: 'p6',
    title: 'Plantillas de Diseño para Redes Sociales',
    description: 'Más de 50 plantillas editables para Canva y Photoshop. Diseñadas profesionalmente para aumentar la interacción en Instagram, Facebook y Twitter.',
    price: 650.00,
    format: Category.PDF,
    excerpt: '50+ plantillas editables para Canva y Photoshop.',
    thumbnail: 'https://picsum.photos/seed/templates/600/400',
    rating: 4.8,
    reviews: 22,
    comments: [],
  },
];

export const CATEGORIES = Object.values(Category);
